export const PostsData = [
  {
    id: 1,
    img: "/assets/gn.jpeg",
    name: "Dr-Gn-Abid",
    official: "Official audio",
    days: "2d",
    likes: "230,333 likes",
    follow: "Suggested for you",
  },
  {
    id: 2,
    img: "/assets/user2.jpg",
    name: "Zafar",
    official: "Origional Audio",
    days: "4d",
    likes: "220,333 likes",
    follow: "Followed by sajidraza376 + 3 mo...",
  },
  {
    id: 3,
    img: "/assets/user3.jpg",
    name: "sonam-Bajwa",
    official: "Official video",
    days: "3d",
    likes: "290,333 likes",
    follow: "Suggested for you",
  },
  {
    id: 4,
    img: "/assets/user4.jpg",
    name: "Aliya Butt",
    official: "Official Content",
    days: "5d",
    likes: "234,333 likes",
    follow: "muhammadarslan3896Following nazg2004 + 4 more",
  },
  {
    id: 5,
    img: "/assets/user5.jpg",
    name: "Niaz Mughal",
    official: "Official",
    days: "7d",
    likes: "130,333 likes",
    follow: "Suggested for you",
  },
  {
    id: 6,
    img: "/assets/user6.jpg",
    name: "Nisar-Mughal",
    official: "Stduio",
    days: "1d",
    likes: "530,333 likes",
    follow: "Followed by sajidraza376 + 3 mo...",
  },
  {
    id: 7,
    img: "/assets/user7.jpg",
    name: "Ali Raza",
    official: "Official",
    days: "7d",
    likes: "430,333 likes",
    follow: "Followed by shakeelahmad786 + 3 mo...",
  },
];
